name: Run Jupyter Notebook

on:
  push:
    branches:
      - main

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install jupyter nbconvert pandas numpy matplotlib seaborn
      - name: Run notebook
        run: |
          jupyter nbconvert --to notebook --execute credit_default_eda.ipynb