name: Run Jupyter Notebook

on:
  push:
    branches:
      - main

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install jupyter nbconvert pandas numpy matplotlib seaborn flake8 black
      - name: Run Flake8
        run: |
          flake8 .  # Adjust the path if needed to target specific files or directories

      - name: Run Black
        run: |
          black --check .  # This checks for formatting issues without modifying files

      - name: Run notebook and convert to HTML
        run: |
          jupyter nbconvert --to notebook --execute credit_default_eda.ipynb
          jupyter nbconvert --to html credit_default_eda.ipynb --output-dir=.