name: Run Jupyter Notebook

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Убедитесь, что есть права на запись

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install jupyter nbconvert pandas numpy matplotlib seaborn flake8 black
      - name: Run Flake8
        run: |
          #flake8 .  # Adjust the path if needed to target specific files or directories
          flake8 --max-line-length=88 --ignore=E203,W503 . # Игнорируем некоторые ошибки, чтобы избежать конфликтов с Black

      - name: Run Black
        run: |
          #black --check .  # This checks for formatting issues without modifying files
          black --check --line-length 88 .  # Проверка форматирования с учетом длины строки 88 символов

      - name: Run notebook and convert to HTML
        run: |
          jupyter nbconvert --to notebook --execute credit_default_eda.ipynb
          jupyter nbconvert --to html credit_default_eda.ipynb --output-dir=.

      - name: Commit and push HTML file
        run: |
          git config --local user.email "maksimsazonov476@gmail.com"
          git config --local user.name "VoroninMaxim"
          git add credit_default_eda.html  # Добавьте сгенерированный HTML файл
          git commit -m "Add generated HTML report from Jupyter notebook"
          git pull origin main  # Сначала выполните pull, чтобы синхронизироваться с удаленным репозиторием
          git push origin main  # Затем выполните push
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_ACCESS_TOKEN }}  # Используйте GITHUB_TOKEN для аутентификации